services:
  - type: web
    name: recapp-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/users/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES_IN
        value: '90'
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_ACCESS_TOKEN
        sync: false
      - key: TMDB_BASIC_URL
        value: https://api.themoviedb.org/3/
      - key: EMAIL_FROM
        sync: false
      - key: SENDGRID_USERNAME
        value: apikey
      - key: SENDGRID_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CALLBACK_URL
        sync: false # https://<your-server>.onrender.com/api/v1/users/auth/google/callback
      - key: ORIGIN_URL
        sync: false # https://<your-client>.onrender.com
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: recapp-redis
          property: connectionString

  - type: redis
    name: recapp-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
